[tool.poetry]
name = "nlp-text-reconstruction"
version = "0.1.0"
description = "Assignment of Natural Language Processing | UniPi 2025"
authors = [
    {name = "Nikolaos Ioannis Giannakopoulos",email = "nikolas.giannakopoulos@hotmail.com"}
]
readme = "README.md"
packages = [{include = "nlp_reconstruction"}]

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.1.0"
transformers = "^4.35.0"
tokenizers = "^0.15.0"
pandas = "^2.1.0"
numpy = "^1.24.0"
matplotlib = "^3.7.0"
seaborn = "^0.12.0"
scikit-learn = "^1.3.0"
nltk = "^3.8.0"
jiwer = "^3.0.0"
bert-score = "^0.3.13"
sentence-transformers = "^2.2.0"
gensim = "^4.3.0"
tqdm = "^4.66.0"
datasets = "^2.14.0"
accelerate = "^0.24.0"
safetensors = "^0.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
flake8 = "^6.0.0"
mypy = "^1.5.0"
jupyter = "^1.0.0"
ipykernel = "^6.25.0"

[tool.poetry.group.gpu]
optional = true

[tool.poetry.group.gpu.dependencies]
torch = {version = "^2.1.0", source = "pytorch-gpu"}

[[tool.poetry.source]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--strict-config",
    "--verbose",
]

[tool.poetry.scripts]
run-reconstruction = "nlp_reconstruction.main:main"
evaluate-methods = "nlp_reconstruction.evaluation:main"